### ISSUE TITLE
Postgres insert data contains double quotation marks

### ISSUE THREAD

**Issue by kosza** [sipcapture/heplify-server#256]
Hi All,

The call-id can contain many special characters, like double quotation marks.
In the mysql insert sql the double quotation mark gets an escape character (\) but in the postgres sql. That is why the postgres throw an error during insert.

from postgres log:
2019-07-02 13:02:02.620 UTC [60752] homer@homer_data ERROR:  invalid input syntax for type json
2019-07-02 13:02:02.620 UTC [60752] homer@homer_data DETAIL:  Token "aQ1020215020lpbcGhEfIhNgI0l" is invalid.
2019-07-02 13:02:02.620 UTC [60752] homer@homer_data CONTEXT:  JSON data, line 1: ..._user":"","callid":"'"aQ1020215020lpbcGhEfIhNgI0l...
        COPY hep_proto_1_call, line 12, column data_header: "{"ruri_domain":"xxx.xxx.xxx.xxx","ruri_user":"1272","from_user":"+3630443xxxx","to_user":"+3601272","pid_..."
2019-07-02 13:02:02.620 UTC [60752] homer@homer_data STATEMENT:  COPY hep_proto_1_call(sid,create_date,protocol_header,data_header,raw) FROM STDIN

Best regards,
Szabolcs

**Comment by negbie** [comment]
Hi koza,
thanks for the report. Would it be possible to do a pr for that from your side? Sounds pretty trivial. I have only very little time for the next months and cannot help as much as I usually do.

**Comment by negbie** [comment]
As a starting point please have a look at this function:
https://github.com/sipcapture/heplify-server/blob/master/decoder/decoder.go#L156

**Comment by negbie** [comment]
And here:
https://github.com/sipcapture/heplify-server/blob/master/database/postgres.go#L403

**Comment by kosza** [comment]
I try to investigate it.
What does pr mean?

**Comment by negbie** [comment]
pull request

**Comment by hbokh** [comment]
@negbie Has this been fixed yet? I ask because I don't see any PR here, but I do see the same issue on the latest heplify-server 1.12:

```
2019-12-22 16:47:29.088 CET [32241] homer@homer_data ERROR:  invalid input syntax for type json
2019-12-22 16:47:29.088 CET [32241] homer@homer_data DETAIL:  Token "Repair" is invalid.
2019-12-22 16:47:29.088 CET [32241] homer@homer_data CONTEXT:  JSON data, line 1: ...ri_domain":"","ruri_user":"","from_user":""Repair...
2019-12-22 16:47:29.088 CET [32241] homer@homer_data STATEMENT:  COPY hep_proto_1_registration(sid,create_date,protocol_header,data_header,raw) FROM STDIN
```

**Comment by negbie** [comment]
Hi @hbokh 
it's because I only escape callid, user_agent, server, content_type, reason

You can see it here:
https://github.com/sipcapture/heplify-server/blob/master/decoder/decoder.go#L177

**Comment by negbie** [comment]
Not looked it up but it seems your domain (xmlns="http... and name="contactCard...) part is against ABNF specification, isn't it? But it should be no problem to escape the ruri_domain aswell

**Comment by hbokh** [comment]
Thanks Eugen!
They seem to come from a `User-Agent: UCCAPI/2.0.6362.123`, which is something Microsoft related, possibly "Lync" (educated guess).

**Comment by negbie** [comment]
@hbokh latest commit escapes ruri_domain aswell but I'm not sure if not maybe the whole message is invalid, like here for example: https://www.msxfaq.de/skype_for_business/trace/siptrace-ocslogon.html

and search for
xmlns="http or name="contactCard

You will find both but not in request line.

**Comment by hbokh** [comment]
Thanks, that works for `ruri_domain` in v1.13.
Next up is `from_user`... 🤪

```
2019-12-23 13:50:22.590 CET [24883] homer@homer_data ERROR:  invalid input syntax for type json
2019-12-23 13:50:22.590 CET [24883] homer@homer_data DETAIL:  Token ">" is invalid.
2019-12-23 13:50:22.590 CET [24883] homer@homer_data CONTEXT:  JSON data, line 1: ...00089","ruri_domain":"10.1.2.134","from_user":"">...
	COPY hep_proto_1_call, line 976, column data_header: "{"ruri_user":"123400089","ruri_domain":"10.1.2.134","from_user":""> Some Username" <sip:07012345..."
2019-12-23 13:50:22.590 CET [24883] homer@homer_data STATEMENT:  COPY hep_proto_1_call(sid,create_date,protocol_header,data_header,raw) FROM STDIN
```

Now I'm hardly a programmer, but maybe I can try and fix this myself on the ones that still cause issues.
Is there a reason why I should NOT use `escape` on a particular tag in these lines?
https://github.com/sipcapture/heplify-server/blob/master/decoder/decoder.go#L177-L227

**Comment by negbie** [comment]
It will save some nanoseconds processing time but I think it's worth to just escape all header. So did I with the latest commit ;)

**Comment by hbokh** [comment]
Great! Danke schön!!
When can we expect a new binary release of v1.13?
I ask because we use the official binary in our SaltStack-states:

```
# Use the official build heplify-server binary from Sipcature. There is no
# file sha256sums.txt available, so check and change this with new releases!
{% with version, source_hash = ('1.12', '04466bd5651e78bff904995161df255cf0a2fb7dae4f3db53aff7ed05956c852') %}
/usr/local/bin/heplify-server:
  file.managed:
    - source: https://github.com/sipcapture/heplify-server/releases/download/{{ version }}/heplify-server
    - source_hash: {{ source_hash }}
    - makedirs: True
    - mode: '0755'
    - group: root
    - user: root
{% endwith %}
```
